### ISSUE TITLE
Intsall issue

### ISSUE THREAD

**Issue by GrandArbiter** [Cojac/Cojac#2]
I downloaded the cojac folder and copied under my valgrind folder, adapt relevant parameters following your tips. Then install valgrind.
It is okay to run valgrind --tool=memchek, but run valgrind --tool=cojac, an error occurred:
     for platform 'x86-linux': No such file or directory

Could you please help whit it?
Thanks in advance

**Comment by frederic-bapst** [comment]
I'm not sure I understand, maybe there is a confusion about two different projects on github:
- Cojac is a tool for Java/JVM. See https://github.com/Cojac/Cojac/wiki
- Cojac-grind is a Valgrind tool; this prototype is much much more experimental; you need to recompile an adapted version of Valgrind. See https://github.com/Cojac/cojac-grind/wiki/Cojacgrind-User-Guide.

Hope it clarifies a bit. 
All the best.

**Comment by GrandArbiter** [comment]
Regarding your second tips, an error occurred during 'make',below is error message:
oa_callbacks_F32.c: In function ‘check_F32_Sqrt’:
oa_callbacks_F32.c:149:3: error: impossible constraint in ‘asm’

So what should I do next...
Thanks.

**Comment by frederic-bapst** [comment]
I propose to close the issue here, and to switch instead to https://github.com/Cojac/cojac-grind/issues/1
See you there!
